# Find Rules:  https://github.com/sasstools/sass-lint/tree/master/docs/rules
# Find Sass-Lint https://github.com/sasstools/grunt-sass-lint

# == active rules =============================================================================================================

rules:
  declarations-before-nesting: 1
  extends-before-declarations: 1
  mixins-before-declarations: 1
  one-declaration-per-line: 1
  extends-before-mixins: 1
  space-between-parens: 1
  space-before-colon: 1
  space-before-brace: 1
  no-vendor-prefixes: 1
  trailing-semicolon: 1
  no-empty-rulesets: 1
  space-after-comma: 1
  space-after-colon: 1
  no-color-keywords: 1
  pseudo-element: 1 # See MDN - https://developer.mozilla.org/en-US/docs/Web/CSS/Pseudo-elements
  no-url-domains: 1
  final-newline: 1
  leading-zero: 1
  class-name-format:
    - 1
    - convention: hyphenatedbem # Default: hyphenatedlowercase
  property-units:
    - 1
    - global:
      - 'px'
      - 'em'
      - 'rem'
      - 'vh'
      - 'vw'
      - '%'
      - 's'
  hex-length:
    - 1
    - style: 'long'
  nesting-depth:
    - 1
    - max-depth: 3 # Default: 3 - optimized for bem
  no-misspelled-properties:
    - 1
    - extra-properties:
      - 'touch-callout'
      - 'overflow-scrolling'

# == disabled rules ===========================================================================================================
  empty-line-between-blocks: 0
  single-line-per-selector: 0
  force-attribute-nesting: 0
  no-duplicate-properties: 0
  placeholder-name-format: 0
  no-qualifying-elements: 0
  force-element-nesting: 0
  placeholder-in-extend: 0
  variable-name-format: 0
  force-pseudo-nesting: 0
  property-sort-order: 0
  mixin-name-format: 0
  no-css-comments: 0
  indentation: 0
  shorthand: 0
  no-ids: 0

